apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceNameFront }}-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: {{ .Values.fqdn }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.serviceNameFront }}
            port: 
              number: 80